### ISSUE TITLE
PDF Index wrong encoding of utf-8

### ISSUE THREAD

**Issue by kreativmonkey** [wbh-community/wbhdoc#13]
Das PDF-Metadata-Inhaltsverzeichnis (also zum Navigieren im PDF Dokument, nicht das abgebildete) verträgt keine Umlaute.

![grafik](https://user-images.githubusercontent.com/8607439/209293893-9865a66a-d5be-4309-b4b3-7d794f17f537.png)

**Comment by polarvogel** [comment]
thanks for the fix, just in this minute I uploaded an alternative solution:
https://github.com/wbh-community/pandoc-wbh-template/issues/59#issue-1517442444
