### ISSUE TITLE
Echoing the reason for pandoc build failures will be cut off

### ISSUE THREAD

**Issue by polarvogel** [wbh-community/wbhdoc#14]
The pandoc command is called in line 109 of entrypoint.sh. If this command failes, the fuction "buildFailed()" will be called with the error output of the pandoc command as a parameter.

When echoing the parameter in line 68 to the user, '$1' is used to get the contents of the parameter, given to the buildFailed() function. This results in cutting the output after the first word / space character, the user will not get the full message.

Replace `echo $1` with `echo "$@"` to print the complete message.

https://github.com/wbh-community/wbhdoc/blob/2a8e732e0e59e76307430ce2924cef548c167c7d/entrypoint.sh#L78

See screenshot. Top command is the original '$1' version, bottom command changes '$1' to "$@" (with " within the code):

![Unbenannt](https://user-images.githubusercontent.com/6965769/210366993-7894d0c2-5663-4d04-bd01-713b00aabf12.PNG)

**Comment by kreativmonkey** [comment]
thank you for reporting this issue and the solution. in the future you can create a pull-request with your changes.
